### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by xmnlab** [omnisci/pyomnisci#7]
hi everyone!

I am implementing pyomnisci to ibis-omniscidb and I had this issue:

```
E       TypeError: load_table() missing 1 required positional argument: 'column_names'
```

it seems it was already fixed on master. Is there any plan for the next release?

**Comment by jclay** [comment]
Hi @xmnlab v0.27.0 was just released: https://github.com/omnisci/pyomnisci/releases/tag/v0.27.0

Please re-open if the issue persists.

**Comment by xmnlab** [comment]
that is a great news. thanks!
